---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5

suites:
  - name: standalone
    run_list:
      - recipe[base_test]
      - recipe[chef_server::default]
      - recipe[admin_org_test]
      - recipe[chef_server::manage]
      - recipe[chef_server::reporting]
      - recipe[analytics_test]
      - recipe[chef_server::_analytics_chef_server]
    attributes:
      chef_server:
        backend_vip: '33.33.33.10'
    driver_config:
      require_chef_omnibus: true
      network:
      - ["private_network", {ip: "33.33.33.10"}]

  - name: analytics
    run_list:
      - recipe[base_test]
      - recipe[chef_server::analytics]
    attributes:
    driver_config:
      require_chef_omnibus: true
      network:
      - ["private_network", {ip: "33.33.33.11"}]