---
driver:
  name: vagrant

driver_config:
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: standalone
    run_list:
      - recipe[chef_server::default]
      - recipe[chef_server::add_ons]
      - recipe[test::user_and_org]
    attributes:
      add_ons:
        - opscode-manage
    driver_config:
      network:
        - ["private_network", {ip: "33.33.33.10"}]

  - name: analytics
    run_list:
      - recipe[chef_server::default]
      - recipe[chef_server::add_ons]
    attributes:
      add_ons:
        - opscode-analytics
    driver_config:
      network:
        - ["private_network", {ip: "33.33.33.11"}]

  - name: delivery
    run_list:
      - recipe[chef_server::default]
      - recipe[chef_server::add_ons]
    attributes:
      add_ons:
        - opscode-manage
        - opscode-reporting
        - opscode-push-jobs-server
    driver_config:
      network:
        - ["private_network", {ip: "33.33.33.12"}]